### ISSUE TITLE
Taking over, and ESMification

### ISSUE THREAD

**Issue by philsturgeon** [readmeio/json-schema-ref-parser#64]
Thanks for picking up the mantle here. I've been trying to get somebody to take this package off my hands for over a year.

If you can merge https://github.com/APIDevTools/json-schema-ref-parser/pull/295 I'll be happy to deprecate the package and point it your way.

**Comment by erunion** [comment]
Sure, we've been a bit hesitant to adopt ESM but I'll see what I can do.

**Comment by philsturgeon** [comment]
@erunion somewhat good news, the @ApiDevTools version has got two new maintainers, they're going full https://github.com/APIDevTools/json-schema-ref-parser/pull/300 for a v11. Perhaps work with them, or do your own thing, or work together on the idillic modern JSON Schema $id/$ref future that https://github.com/APIDevTools/json-schema-reader was meant to sort out, but I'll be off the project as Protect Earth is taking over my life.
